### ISSUE TITLE
Azure VM: "Paste the Public IP address in your browser" not working

### ISSUE THREAD

**Issue by AlexandreSajus** [EY-Data-Science-Program/2021-Better-Working-World-Data-Challenge#31]
I have followed the tutorials 1b and 2a of the wiki to create a data science environment. I am stuck at step 4 of 2a where "Paste the Public IP address in your browser." isnt working. I get an error "Site can't be reached". 

![image](https://user-images.githubusercontent.com/62465003/113517833-ad41f480-9582-11eb-9a4b-66752a7821e1.png)
![image](https://user-images.githubusercontent.com/62465003/113517767-51776b80-9582-11eb-88e8-ad5ca8c818a8.png)

Where did I go wrong?

**Comment by glowglowglow** [comment]
Hi there!
Can you please try deleting this environment, and redeploying one using Australia East as your Location?

**Comment by AlexandreSajus** [comment]
Same thing in Australia East unfortunately

**Comment by glowglowglow** [comment]
For issues related to deployment, please check out this page - https://github.com/EY-Data-Science-Program/2021-Better-Working-World-Data-Challenge/wiki/4a.-Troubleshooting:-FAQ

**Comment by Jimut123** [comment]
@AlexandreSajus  I had the same problem, and got it resolved via SSH
```
$ ssh -i <your-private-key>.pem ubuntu@<your-public-ip>
$ cd /opt/odc/   # This is where the code resides
$ jupyter-notebook --no-browser --port=8888  # forward it to your machine!
# ssh -N -f -L localhost:8888:localhost:8888 jimutbp@192.168.43.255  # in case
# fire up localhost:8888
```
fire up localhost:8888 in your browser to get the data

**Comment by AlexandreSajus** [comment]
THIS IS A REALLY IMPORTANT SECURITY ISSUE, PLEASE LOOK INTO IT
I found the problem:
My password for the Azure VM was something like "&WORD". When I checked the logs of the VM, I found: "/bin/sh: 1: WORD: not found.
The console considered my password as a command because of the symbol "&" and saved it in the logs unencrypted

Solution: don't start your password with a "&"
