### ISSUE TITLE
Removing myself from a team

### ISSUE THREAD

**Issue by Aditya-Jha2002** [EY-Data-Science-Program/2021-Better-Working-World-Data-Challenge#79]
I by mistake requested a team to merge with me, instead of clicking my friend.
I tried to find how to remove the request, but was unable to do so.
And then that team accepted.
I have not collaborated with them till now, It happened today.
Is there anyway the EY team could remove me from that team???

**Comment by EY-glowglowglow** [comment]
Hi there,
Please send an email to eydatasciencechallenge@au.ey.com with your username and the names of the team that you have mistakenly joined.
